### PR TITLE
sec: Share key parsing code for sign / enc

### PR DESCRIPTION
**Pull request by ccollins476ad**

### CODE REVIEW

**Comment by utzig** [comment]
@ccollins476ad Please rebase; seems like you had already fixed some of the EC issues, sorry haven't seen this before!

**Comment by ccollins476ad** [comment]
Whoa... I totally forgot about this.  Well, I rebased.  Do you know a good way to test this? :)

**Comment by utzig** [comment]
I tested `rsa`, `ec256` and `ed25519` and everything is working. My issue is that this is bringing back the "custom" ed25519 ASN1 parsing routines, and still have to look at other changes...

**Comment by ccollins476ad** [comment]
I honestly can't tell what the point of this PR is anymore :).  I'm just going to close it.  Thanks for looking at it.

**Pull request closed without merging**
